number_of_males = int(input('Enter number of males: '))
number_of_females = int(input('Enter number of females: '))
total= (number_of_males+number_of_females)
print('Total: ',total)
print('**********************************************************')
per_of_males =float((number_of_males/total)*100)
per_of_females =float((number_of_females/total)*100)
print('PERCENTAGE OF MALES ARE: ',per_of_males,'%')
print('PERCENTAGE OF FEMALES ARE: ',per_of_females,'%')